packages/server/schema.gql
packages/server/src/modules/auth/auth.service.ts
packages/server/src/modules/classwork/classwork.module.ts
packages/server/src/modules/classwork/classwork.service.ts
packages/server/src/modules/classwork/classwork.type.ts
packages/server/src/modules/classwork/classworkMaterial.resolver.ts
packages/server/src/modules/classwork/models/ClassworkMaterial.ts

Link task: https://app.clickup.com/t/89xg19

Implement classworkservice.findAndPaginateClassworkMaterial

---

packages/server/schema.gql
packages/server/src/modules/classwork/classwork.type.ts
packages/web/src/graphql/generated.tsx
packages/web/src/modules/CreateClassworkAssignment/CreateClassworkAssignment.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkAssignments/ClassworkAssignments.tsx

Link task: https://app.clickup.com/t/8vue2y

Update create classwork assignment

---

packages/web/src/@kathena/ui/Select/Select.tsx
packages/web/src/@kathena/ui/SelectFormField/SelectFormField.tsx
packages/web/src/modules/AccountProfile/UpdateAccountDialog.tsx
packages/web/src/modules/CreateUpdateAccount/CreateAccountDialog.tsx

Link task: https://app.clickup.com/t/8xyb0m

Update UI Support Multiple Role

---

packages/server/src/modules/classwork/classwork.service.spec.ts

link task: https://app.clickup.com/t/8zz5b0

Write unit test for findAndPaginateClassworkMaterials

---

packages/server/src/modules/classwork/classwork.service.spec.ts
packages/server/src/modules/classwork/classwork.service.ts

Linktask: https://app.clickup.com/t/93w2gg

 update findClassworkMaterialById and findClassworkAssignmentById

---

packages/server/schema.gql
packages/server/src/modules/classwork/classwork.service.ts
packages/server/src/modules/classwork/classwork.type.ts
packages/server/src/modules/classwork/classworkSubmission.resolver.ts
packages/server/src/modules/classwork/models/ClassworkSubmission.ts

Task linked: [CU-93yca2 Add comment to classworkSubmision](https://app.clickup.com/t/93yca2)

Add comment to classwork submision

---

packages/server/schema.gql
packages/server/src/modules/classwork/classworkSubmission.resolver.ts
packages/web/src/graphql/generated.tsx
packages/web/src/modules/ClassworkAssignmentDetail/ClassworkAssignmentDetail.gql
packages/web/src/modules/ClassworkAssignmentDetail/ClassworkAssignmentDetail.tsx
packages/web/src/utils/path-builder.ts

Link task: https://app.clickup.com/t/90300u

Add List submissions

---

packages/web/src/modules/TeachingCourse/Components/General/General.tsx

Link task: https://app.clickup.com/t/9bv3ry

Add comment to teaching course

---

packages/web/src/modules/ClassworkAssignmentDetail/ClassworkAssignmentDetail.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkSubmissionDetail/ClassworkSubmissionDetail.tsx

Link task: https://app.clickup.com/t/940pmu

Add comment to class work submission

---

packages/web/src/modules/StudyingCourse/Components/General/General.tsx

Link task: https://app.clickup.com/t/9bv5xf

Add comment to studying course

---

packages/server/schema.gql
packages/server/src/modules/academic/course.resolver.ts
packages/web/src/graphql/generated.tsx
packages/web/src/modules/TeachingCourse/Components/General/CourseDetailGeneral.gql
packages/web/src/modules/TeachingCourse/Components/General/General.tsx

Link task: https://app.clickup.com/t/9bvvcb

Implement chart average score of each exercise in the course

---

packages/web/src/modules/OrgWorkspace/OrgWorkspace.route.tsx
packages/web/src/modules/StudyingCourse/Components/ClassworkMaterials/ClassworkMaterials.tsx
packages/web/src/modules/StudyingCourse/Components/ClassworkMaterials/DetailContentClassworkMaterial.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkMaterials/DetailClassworkMaterials.tsx
packages/web/src/utils/path-builder.ts

Link task: https://app.clickup.com/t/9bwmcy
UI :
UI add comment: 
UI done:

Add comment to classwork material studying

---

packages/server/schema.gql
packages/server/src/modules/classwork/classwork.service.spec.ts
packages/server/src/modules/classwork/classwork.service.ts
packages/server/src/modules/classwork/classworkSubmission.resolver.ts

Task linked: [CU-9e01vm [BE] add classwordservice.findOneClassworkclassworkSubmission](https://app.clickup.com/t/9e01vm)

[BE] add classwordservice.findOneClassworkclassworkSubmission

---

packages/server/schema.gql
packages/server/src/core/utils/string.ts
packages/server/src/modules/academic/academic.service.spec.ts
packages/server/src/modules/account/account.const.ts
packages/server/src/modules/account/account.module.ts
packages/server/src/modules/account/account.resolver.ts
packages/server/src/modules/account/account.service.spec.ts
packages/server/src/modules/account/account.service.ts
packages/server/src/modules/account/models/Account.ts
packages/server/src/modules/classwork/classwork.service.ts
packages/server/src/modules/mail/mail.service.spec.ts
packages/server/src/modules/mail/mail.service.ts
packages/server/src/modules/mail/templates/activeAccount.hbs
packages/server/src/modules/mail/templates/resetPassword.hbs
packages/web/src/App.route.tsx
packages/web/src/common/auth/AuthContext.tsx
packages/web/src/common/auth/auth.gql
packages/web/src/graphql/generated.tsx
packages/web/src/modules/ResetPassword/ResetPassword.form.tsx
packages/web/src/modules/SetPassword/SetPassword.form.tsx
packages/web/src/modules/SetPassword/SetPassword.tsx
packages/web/src/modules/SetPassword/index.ts
packages/web/src/utils/path-builder.ts
yarn.lock

Link task: https://app.clickup.com/t/9c3enn

As a user, I want to change/set password by OTP

---

packages/server/package.json
packages/server/schema.gql
packages/server/src/core/app/graphql-with-upload.module.ts
packages/server/src/modules/comment/comment.resolver.ts
packages/web/.env.example
packages/web/.gitignore
packages/web/src/common/apollo.tsx
packages/web/src/components/Comment/Comment.gql
packages/web/src/graphql/generated.tsx
packages/web/src/modules/ClassworkAssignmentDetail/ClassworkAssignmentDetail.tsx
packages/web/src/modules/CreateComment/CreateComment.tsx
packages/web/src/modules/StudyingCourse/Components/ClassworkAssignments/DetailContentClassworkAssignment.tsx
packages/web/src/modules/StudyingCourse/Components/ClassworkMaterials/DetailContentClassworkMaterial.tsx
packages/web/src/modules/StudyingCourse/Components/General/General.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkMaterials/DetailClassworkMaterials.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkSubmissionDetail/ClassworkSubmissionDetail.tsx
packages/web/src/modules/TeachingCourse/Components/General/General.tsx
yarn.lock

Link task : https://app.clickup.com/t/9y2k1x

Realtime comment and refactor comment

---

packages/server/schema.gql
packages/server/src/core/app/app.module.ts
packages/server/src/modules/academic/academic.module.ts
packages/server/src/modules/academic/academic.service.spec.ts
packages/server/src/modules/academic/academic.service.ts
packages/server/src/modules/academic/lesson.resolver.ts
packages/server/src/modules/academic/models/Lesson.ts
packages/server/src/modules/classwork/classwork.service.ts
packages/server/src/modules/classwork/classworkMaterial.resolver.ts
packages/server/src/modules/classwork/models/Classwork.ts
packages/server/src/modules/rating/models/rating.ts
packages/server/src/modules/rating/rating.module.ts
packages/server/src/modules/rating/rating.resolver.ts
packages/server/src/modules/rating/rating.service.spec.ts
packages/server/src/modules/rating/rating.service.ts

Link task: 
https://app.clickup.com/t/ac28m6
https://app.clickup.com/t/ac28n1

Implement Lesson module and Rating module

---

.vscode/settings.json
packages/server/schema.gql
packages/server/src/modules/auth/auth.service.ts
packages/server/src/modules/rating/rating.const.ts
packages/server/src/modules/rating/rating.module.ts
packages/server/src/modules/rating/rating.resolver.ts
packages/server/src/modules/rating/rating.service.spec.ts
packages/server/src/modules/rating/rating.service.ts

- Add role test handler for assessment for lesson
- Add function createRatingForLesson
- Convert createRating function to shared function
Link task: https://app.clickup.com/t/chzava

CU-chzava - [BE] Implement authService.canSubmitRating

---

packages/server/schema.gql
packages/server/src/modules/academic/academic.service.spec.ts
packages/server/src/modules/academic/academic.service.ts
packages/server/src/modules/academic/models/Course.ts
packages/server/src/modules/academic/models/Lesson.ts
packages/server/src/modules/classwork/models/Classwork.ts
packages/server/src/modules/classwork/models/ClassworkSubmission.ts
packages/server/src/modules/conversation/conversation.service.spec.ts
packages/server/src/modules/conversation/model/Conversation.ts
packages/server/src/modules/rating/models/Rating.ts
packages/server/src/modules/rating/rating.service.spec.ts
yarn.lock

Link task: https://app.clickup.com/t/e5knaw

Cu e5knaw be update id fields to object

---

packages/server/schema.gql
packages/server/src/modules/academic/academic.service.spec.ts
packages/server/src/modules/academic/academic.service.ts
packages/server/src/modules/academic/lesson.resolver.ts
packages/server/src/modules/academic/models/Lesson.ts
packages/server/src/modules/classwork/classwork.service.spec.ts

Task linked: [CU-bng7j6 [BE] Implement academicService.findLessonById](https://app.clickup.com/t/bng7j6)

[BE] Implement academicService.findLessonById

---

packages/server/schema.gql
packages/server/src/modules/academic/academic.service.spec.ts
packages/server/src/modules/academic/academic.service.ts
packages/server/src/modules/academic/lesson.resolver.ts
packages/server/src/modules/academic/models/Lesson.ts
packages/server/src/modules/rating/rating.service.spec.ts
yarn.lock

Link task: https://app.clickup.com/t/f7vek7

Add check the permission to use lesson functions

---

packages/server/schema.gql
packages/server/src/modules/academic/academic.service.spec.ts
packages/server/src/modules/academic/academic.service.ts
packages/server/src/modules/academic/lesson.resolver.ts

remove check canAccountManageCourse

[BE] Update findLessonById

---

packages/web/src/graphql/generated.tsx
packages/web/src/modules/OrgWorkspace/OrgWorkspace.route.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/ClassworkLessions.gql
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/ClassworkLessons.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/CreateClassworkLesson.form.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/CreateClassworkLesson.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/DetailClassworkLesson.tsx
packages/web/src/utils/path-builder.ts

UI List Lesson: 
UI Create Lesson:
UI Done Create Lesson:

Cu gnp09r fe create lesson

---

packages/server/schema.gql
packages/server/src/modules/lesson/models/Lesson.ts

Add fields:
- materialListBeforeClass [ ]
- materialListInClass [ ]
- materialListAfterClass [ ]
- classworkAssigmentListBeforeClass [ ]
- classworkAssigmentListInClass [ ] 
- classworkAssigmentListAfterClass [ ]

CU-j3drru - [BE] Update Lesson model

---

packages/web/src/graphql/generated.tsx
packages/web/src/modules/CourseList/CourseList.gql
packages/web/src/modules/CourseList/CourseList.tsx
packages/web/src/modules/OrgWorkspace/components/OrgSidebar.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/ClassworkLessions.gql
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/DetailClassworkLesson.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/LessonDisplayName/AssignmentDisplayName.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/LessonDisplayName/MaterialDisplayName.tsx
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/LessonDisplayName/useAssignmentUtils.ts
packages/web/src/modules/TeachingCourse/Components/ClassworkLessons/LessonDisplayName/useMaterialUtils.ts

Cu j3jth2 fe detail list of lessons before after classes material

---

packages/server/src/modules/classwork/models/Classwork.ts

Add fields:
- **iframeVideo[]:** require:false, nullable:true, default: null

CU-j3dz57 - [BE] Update Classwork model

---

packages/server/schema.gql
packages/server/src/modules/course/course.resolver.ts
packages/server/src/modules/course/course.service.spec.ts
packages/server/src/modules/course/course.service.ts

Link task: https://app.clickup.com/t/m8933c

CU-m8933c - [BE] Implement courseService.updateCoursePublicationById

---

packages/server/schema.gql
packages/server/src/modules/classwork/classwork.service.spec.ts
packages/server/src/modules/classwork/classwork.service.ts
packages/server/src/modules/classwork/classwork.type.ts
packages/server/src/modules/classwork/models/Classwork.ts

Add fields iframeVideos[] (nullable:true) when creating

[BE] Update classworkService.createClassworkMaterial

---

packages/server/schema.gql
packages/server/src/modules/lesson/lesson.service.spec.ts
packages/server/src/modules/lesson/lesson.service.ts
packages/server/src/modules/lesson/lesson.type.ts

Separate the date list of lessons into a separate function

Separate the date list of lessons into a separate function

---

packages/server/schema.gql
packages/server/src/modules/conversation/conversation.resolver.ts

Link task: https://app.clickup.com/t/1n4z1ht

CU-1n4z1ht - [BE] Fix realtime Subscription (Chat realtime)

---

packages/server/schema.gql
packages/server/src/core/utils/pubSub.ts
packages/server/src/modules/classwork/classworkAssignments.resolver.ts
packages/server/src/modules/classwork/classworkMaterial.resolver.ts
packages/server/src/modules/conversation/conversation.resolver.ts
packages/server/src/modules/conversation/notification.type.ts

Config pubSub

---

packages/server/schema.gql
packages/server/src/modules/lesson/lesson.resolver.ts
packages/server/src/modules/lesson/lesson.service.spec.ts
packages/server/src/modules/lesson/lesson.service.ts

Link task: https://app.clickup.com/t/1napy2z

CU-1napy2z - [BE] Implement lessonSerivce.addLessonToCourse

---

packages/server/src/modules/course/course.service.spec.ts
packages/server/src/modules/course/course.service.ts
packages/server/src/modules/course/models/Course.ts

Link task: https://app.clickup.com/t/1nvxf7c

CU-1nvxf7c - [BE] Error when create course with totalNumberOfTheLesson is too big

---

packages/server/src/modules/course/course.service.spec.ts
packages/server/src/modules/course/course.service.ts
packages/server/src/modules/course/models/Course.ts
packages/server/src/modules/lesson/lesson.service.spec.ts

Fix error when create lesson

---

packages/server/schema.gql
packages/server/src/modules/lesson/lesson.service.spec.ts
packages/server/src/modules/rating/rating.resolver.ts
packages/server/src/modules/rating/rating.service.spec.ts
packages/server/src/modules/rating/rating.service.ts

- Add findOneRating function
- Write unit test
- Fix unit test for lesson

Add findOneRating function

---

packages/server/schema.gql
packages/server/src/modules/auth/__snapshots__/orgRolesMap.spec.ts.snap
packages/server/src/modules/auth/models/Permission.ts
packages/server/src/modules/auth/orgRolesMap.ts
packages/server/src/modules/classwork/classwork.module.ts
packages/server/src/modules/classwork/classwork.service.spec.ts
packages/server/src/modules/classwork/classwork.service.ts
packages/server/src/modules/classwork/classwork.type.ts
packages/server/src/modules/classwork/classworkSubmission.resolver.ts
packages/server/src/modules/classwork/models/ClassworkSubmission.ts

Add submission editing function
